redirect plugin initial commit
resolutionlife/kong-plugin-redirect pull request #1
Opened 2023-02-23 15:53 UTC by abdelhegazi

2023-02-24 10:07 UTC, mattoddie requested changes

2023-02-24 10:07 UTC, mattoddie commented on kong/plugins/url-redirect/handler.lua
> +local BasePlugin = require "kong.plugins.base_plugin"
This file should be in `kong/plugins/redirect` to match the plugin name (redirect vs url-redirect)

2023-02-24 10:07 UTC, mattoddie commented on kong/plugins/url-redirect/schema.lua
> +return {
Can we update this to closer match the schema format in the template https://github.com/Kong/kong-plugin/blob/master/kong/plugins/myplugin/schema.lua

2023-02-24 10:07 UTC, mattoddie commented on kong/plugins/url-redirect/handler.lua
> +local BasePlugin = require "kong.plugins.base_plugin"
Also can the file closer match the template format for handler https://github.com/Kong/kong-plugin/blob/master/kong/plugins/myplugin/handler.lua

2023-02-24 10:07 UTC, mattoddie commented on kong-plugin-redirect-0.1.0-1.rockspec
> +    ["kong.plugins.url-redirect.utils"] = "./kong/plugins/url-redirect/utils.lua"
We don't have `utils` package

2023-02-27 16:32 UTC, mattoddie requested changes

2023-02-27 16:32 UTC, mattoddie commented on kong/plugins/url-redirect/handler.lua
> +RedirectHandler.PRIORITY = plugin.PRIORITY
No need for this line

2023-02-27 16:32 UTC, mattoddie commented on kong/plugins/url-redirect/handler.lua
> +RedirectHandler.VERSION = plugin.VERSION
No need for this line

2023-02-27 16:32 UTC, mattoddie commented on kong/plugins/url-redirect/handler.lua
> +local BasePlugin = require "kong.plugins.base_plugin"
No need for this line

2023-02-27 16:32 UTC, mattoddie commented on kong/plugins/url-redirect/handler.lua
> +function RedirectHandler:new()
```suggestion
function plugin:new()
```

2023-02-27 16:32 UTC, mattoddie commented on kong/plugins/url-redirect/handler.lua
> +function RedirectHandler:access(conf)
```suggestion
function plugin:access(conf)
```

2023-02-27 16:32 UTC, mattoddie commented on kong/plugins/url-redirect/handler.lua
> +return RedirectHandler
```suggestion
return plugin
```

2023-02-27 16:32 UTC, mattoddie commented on kong/plugins/url-redirect/schema.lua
> +              default = "github.com/resolutionlife/kong-plugin-redirect" } },
The request URI you get in `ngx.var.request_uri` is actually the path

```suggestion
              default = "/resolutionlife/kong-plugin-redirect" } },
```

2023-02-28 09:42 UTC, abdelhegazi commented on kong/plugins/url-redirect/handler.lua
> +local BasePlugin = require "kong.plugins.base_plugin"
I guess we need this `BasePlugin` for the redirect

2023-02-28 11:25 UTC, mattoddie requested changes

2023-02-28 11:25 UTC, mattoddie commented on kong/plugins/url-redirect/schema.lua
> +local PLUGIN_NAME = "kong-plugin-redirect"
`kong-plugin-redirect` is repo name, not plugin name

```suggestion
local PLUGIN_NAME = "kong-redirect"
```

2023-02-28 11:25 UTC, mattoddie commented on kong/plugins/url-redirect/handler.lua
> +
```suggestion
```

2023-02-28 11:25 UTC, mattoddie commented on kong-plugin-redirect-0.1.0-1.rockspec
> +    ["kong.plugins.url-redirect.handler"] = "./kong/plugins/url-redirect/handler.lua",
Can we replace all instances of "url-redirect" with just redirect, including plugin folder name?

2023-02-28 11:25 UTC, mattoddie commented on kong-plugin-redirect-0.1.0-1.rockspec
> +package = "kong-plugin-redirect"
I think the plugin template file https://github.com/Kong/kong-plugin/blob/master/kong-plugin-myplugin-0.1.0-1.rockspec is much nicer for all of this as it removes a lot of copy/paste by having variables etc.

2023-02-28 11:25 UTC, mattoddie commented on .github/workflows/test.yaml
> +name: "Test"
Can we remove this file since we have no tests?

2023-03-02 15:27 UTC, mattoddie approved these changes

2023-03-02 15:34 UTC, merged